#!/usr/bin/env bash
# Drive a recorded trace on a real handset, through the real location provider.
#
# This is the device half of V5. `verify_on_device.sh` establishes that the app
# launches, renders and survives; it explicitly SKIPS GPS on a handset —
# "a real handset needs a mock-location provider app; skip rather than pretend" —
# so every number it produced came from a parked phone, which is why V3 and V4
# both closed with "needs a moving car" as a release blocker.
#
# Here the fixes come from a trace generated by the same code that drives the
# JVM scenario suite (`TraceExportTest` <- `ScenarioTraces`), pushed to the
# device, and replayed into `FusedLocationProviderClient.setMockMode` — so
# everything downstream of the satellites is untouched production code: the same
# LocationRequest, the same callback, real `Location` objects with real optional
# fields, the plausibility gate, MapLibre, the Choreographer loop.
#
#   scripts/simulate_drive.sh                          # scenario-a at real time
#   scripts/simulate_drive.sh scenario-h-outage        # one scenario
#   SPEEDUP=8 scripts/simulate_drive.sh scenario-g-jump   # smoke test only
#
# SPEEDUP is for shortening a smoke test and nothing else. It divides the
# interval between fixes without changing the distance between them, so the app
# is shown a vehicle moving that many times faster — a different drive, not the
# same one compressed. Measured at 8x on the S24: the plausibility gate rejected
# 90 of 466 fixes for implying 112 m/s, which produced a deviation and a reroute
# the 1x run does not have. Every scenario result reported anywhere must come
# from a 1x run, and this script says which it was.
set -uo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/toolchain.sh"

PKG=dev.vector.android
ACT="$PKG/.MainActivity"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
TRACES="$ROOT/app/build/traces"
# /data/local/tmp, not shared storage and not the app's external files dir.
#
# Two routes were tried first and both failed for permission reasons worth
# recording, because they are the obvious ones:
#
#  * `/sdcard/Download` — scoped storage. The app cannot read shared storage
#    without READ_EXTERNAL_STORAGE, and putting a storage permission on a
#    navigation app's manifest so a debug harness can work is not a trade worth
#    making. (It also crashed the app the first time, which is fixed
#    independently in MockDrive.load.)
#  * `/sdcard/Android/data/<pkg>/files` — the app's own external directory, and
#    it looks right. But a directory `adb shell mkdir` creates there is owned by
#    shell:ext_data_rw at 0770 on the FUSE layer, so the APP cannot traverse its
#    own directory. `adb shell ls` showed the file present while the app
#    reported "no readable trace", which is a confusing five minutes.
#
# `/data/local/tmp` is `drwxrwx--x`: the `--x` on other lets any process
# traverse it, so a world-readable file inside is readable by the app with no
# permission at all. Nothing else on the device can be affected by what is put
# there, and it is wiped by a factory reset rather than living in the user's
# documents.
DEVDIR=/data/local/tmp/vector-traces
SCENARIO="${1:-scenario-a-city}"
SPEEDUP="${SPEEDUP:-1}"
OUT="${OUT:-$ROOT/build/simulate-drive/$SCENARIO}"
mkdir -p "$OUT"

pass=0; fail=0; skip=0
ok()   { echo "  PASS  $*"; pass=$((pass+1)); }
bad()  { echo "  FAIL  $*"; fail=$((fail+1)); }
note() { echo "        $*"; }
skipf(){ echo "  SKIP  $*"; skip=$((skip+1)); }

echo "=== 0. device and trace ==="
SERIAL="$(adb devices | awk 'NR>1 && $2=="device" {print $1; exit}')"
[ -n "$SERIAL" ] || { echo "no adb device attached"; exit 2; }
MODEL="$(adb -s "$SERIAL" shell getprop ro.product.model | tr -d '\r')"
SDK="$(adb -s "$SERIAL" shell getprop ro.build.version.sdk | tr -d '\r')"
ok "device $SERIAL ($MODEL, API $SDK)"

TRACE="$TRACES/$SCENARIO.csv"
if [ ! -f "$TRACE" ]; then
  echo "no trace at $TRACE"
  echo "generate them with:"
  echo "  ./gradlew :app:testDebugUnitTest --tests 'dev.vector.android.TraceExportTest'"
  exit 2
fi
FIXES=$(grep -vc '^#\|^tMs' "$TRACE")
DUR_MS=$(tail -1 "$TRACE" | cut -d, -f1)
DUR=$((DUR_MS/1000))
WALL=$(python3 -c "print(int($DUR/$SPEEDUP)+45)")
ok "trace $SCENARIO: $FIXES fixes over ${DUR}s, replaying at ${SPEEDUP}x (~${WALL}s wall)"
if [ "$SPEEDUP" != "1" ]; then
  note "TIME-COMPRESSED ${SPEEDUP}x — THIS IS A DIFFERENT DRIVE, NOT THE SAME ONE FASTER."
  note "Compression divides the interval between fixes without changing the"
  note "distance between them, so the app sees a vehicle travelling ${SPEEDUP}x"
  note "faster than the trace describes. Measured at 8x: the plausibility gate"
  note "correctly rejected 90 of 466 fixes as implying 112 m/s, which then"
  note "produced a deviation and a reroute that the 1x run does not have."
  note "Use it to shorten a smoke test. Do not report behaviour or frames from it."
fi

DEST=$(awk -F'\t' -v s="$SCENARIO" '$1==s {print $2}' "$TRACES/destinations.txt")
[ -n "$DEST" ] || { echo "no destination for $SCENARIO in destinations.txt"; exit 2; }
note "destination $DEST"

echo "=== 1. install and permissions ==="
ABI="$(adb -s "$SERIAL" shell getprop ro.product.cpu.abi | tr -d '\r')"
APK="$ROOT/app/build/outputs/apk/debug/app-${ABI}-debug.apk"
[ -f "$APK" ] || APK="$(ls -1 "$ROOT"/app/build/outputs/apk/debug/app-*-debug.apk 2>/dev/null | head -1)"
[ -f "$APK" ] || { echo "no APK built. ./gradlew assembleDebug -PvectorBase=... -PvectorToken=..."; exit 2; }
if adb -s "$SERIAL" install -r -g "$APK" >/dev/null 2>&1; then
  ok "installed $(basename "$APK")"
else
  bad "install failed"; exit 1
fi
adb -s "$SERIAL" shell pm grant $PKG android.permission.ACCESS_FINE_LOCATION 2>/dev/null
adb -s "$SERIAL" shell pm grant $PKG android.permission.ACCESS_COARSE_LOCATION 2>/dev/null

# The OS gate on mock locations. Without this `setMockMode` throws
# SecurityException and the app says so in logcat rather than pretending to
# drive — which is the correct behaviour and also useless for measuring, so the
# harness grants it explicitly and asserts that it took.
adb -s "$SERIAL" shell appops set $PKG android:mock_location allow 2>/dev/null
MOCKOP=$(adb -s "$SERIAL" shell appops get $PKG android:mock_location 2>/dev/null | tr -d '\r')
case "$MOCKOP" in
  *allow*) ok "mock_location granted" ;;
  *) bad "mock_location not granted: $MOCKOP" ;;
esac

# The backend. The APK is built against 127.0.0.1:9003, reached over adb.
adb -s "$SERIAL" reverse tcp:9003 tcp:9003 >/dev/null 2>&1 \
  && ok "adb reverse 9003 -> host" || bad "adb reverse failed"

echo "=== 2. push the trace ==="
adb -s "$SERIAL" shell mkdir -p $DEVDIR >/dev/null 2>&1
if adb -s "$SERIAL" push "$TRACE" "$DEVDIR/$SCENARIO.csv" >/dev/null 2>&1; then
  ok "pushed $(basename "$TRACE")"
else
  bad "push failed"; exit 1
fi
# shell's umask makes a new directory 0700, which the app cannot traverse.
adb -s "$SERIAL" shell chmod 755 "$DEVDIR" >/dev/null 2>&1
adb -s "$SERIAL" shell chmod 644 "$DEVDIR/$SCENARIO.csv" >/dev/null 2>&1

echo "=== 3. launch, settle, then drive ==="
adb -s "$SERIAL" logcat -c
adb -s "$SERIAL" shell am force-stop $PKG

# Pin the camera preferences the run depends on, with the app STOPPED so its
# own cache cannot write them back.
#
# Not tidiness. `verify_on_device.sh` drives the destination flow with taps at
# hardcoded screen fractions, and one of them had toggled the map to NORTH_UP —
# which is a legitimate driver preference, so the app was correctly drawing a
# flat north-up map, and every camera result from this harness was being
# measured under a setting nobody chose deliberately. A validation run has to
# state its own inputs.
adb -s "$SERIAL" shell "run-as $PKG sed -i \
  -e 's|>NORTH_UP<|>HEADING_UP<|' \
  -e 's|>FLAT<|>TILTED<|' shared_prefs/vector.xml" >/dev/null 2>&1
SETTINGS=$(adb -s "$SERIAL" shell "run-as $PKG cat shared_prefs/vector.xml" 2>/dev/null \
  | grep -oP 'name="(orientation|perspective|theme|auto_zoom|voice_mode)"[^/]*' | tr -d '\r' | tr '\n' ' ')
note "settings: $SETTINGS"
adb -s "$SERIAL" shell am start -n "$ACT" >/dev/null 2>&1
sleep 12
adb -s "$SERIAL" shell pidof $PKG >/dev/null 2>&1 && ok "app running" || { bad "app died"; exit 1; }

adb -s "$SERIAL" shell dumpsys meminfo $PKG 2>/dev/null > "$OUT/meminfo-before.txt"
PSS0=$(grep -oP 'TOTAL PSS:\s+\K[0-9]+' "$OUT/meminfo-before.txt" | head -1)

# The trace intent. Delivered to onNewIntent because the activity is singleTop.
adb -s "$SERIAL" shell am start -n "$ACT" \
  --es vectorTrace "$DEVDIR/$SCENARIO.csv" \
  --es vectorDest "$DEST" \
  --es vectorSpeedup "$SPEEDUP" >/dev/null 2>&1
ok "handed the app the trace"

echo "=== 4. driving (${WALL}s) ==="
# Follow logcat for the whole drive rather than dumping the ring buffer at the
# end: the buffer holds minutes, not half an hour, and the long run would lose
# its own beginning.
adb -s "$SERIAL" logcat -v time -s "VectorNav:*" "VectorMock:*" "VectorFrames:*" \
    "AndroidRuntime:E" "ActivityManager:E" > "$OUT/logcat.txt" 2>/dev/null &
LOGPID=$!
END=$(( $(date +%s) + WALL ))
LAST=""
while [ "$(date +%s)" -lt "$END" ]; do
  sleep 15
  adb -s "$SERIAL" shell pidof $PKG >/dev/null 2>&1 || { echo "  !! process died"; break; }
  CUR=$(grep -c 'VectorNav' "$OUT/logcat.txt" 2>/dev/null || echo 0)
  FR=$(grep 'hz=' "$OUT/logcat.txt" 2>/dev/null | tail -1 | grep -oP 'hz=\K[0-9.]+')
  LINE="        $(( (END - $(date +%s)) ))s left · nav events $CUR · ${FR:-–} Hz"
  [ "$LINE" != "$LAST" ] && echo "$LINE" && LAST="$LINE"
done
kill $LOGPID 2>/dev/null
wait $LOGPID 2>/dev/null

echo "=== 5. what the drive did ==="
# Count only what happened BETWEEN the trace's first and last fix.
#
# The window is not tidiness, it is correctness. `MockDrive.stop()` restores
# live mode when the trace ends, and the handset's real position is 2.2 km from
# where the trace leaves the vehicle — so a scenario that is still navigating
# when the trace runs out is handed a genuine 2.2 km deviation and correctly
# goes off route. Scenario E is the one that does this, because a U-turn
# deliberately never arrives, and it was being failed for behaviour that is
# right and that no driver would ever see. (The plausibility gate rejects three
# of those fixes first and then believes the receiver, which is also right.)
#
# Anything after `VectorMock: END` is the handoff back to real GPS, not an event
# of the drive.
awk '/VectorMock.*START fixes=/{on=1} on{print} /VectorMock.*END after/{on=0}' \
  "$OUT/logcat.txt" > "$OUT/logcat-drive.txt" 2>/dev/null
[ -s "$OUT/logcat-drive.txt" ] || cp "$OUT/logcat.txt" "$OUT/logcat-drive.txt" 2>/dev/null
note "drive window: $(wc -l < "$OUT/logcat-drive.txt") of $(wc -l < "$OUT/logcat.txt") log lines"

# `grep -c` prints 0 AND exits non-zero when it matches nothing, so a
# `|| echo 0` fallback appended a SECOND zero and every count became the string
# "0\n0" — which is what "[: 0\n0: integer expected" was.
navcount() { grep -c "VectorNav.*$1" "$OUT/logcat-drive.txt" 2>/dev/null | head -1 || true; }
OFFROUTE=$(navcount 'offroute')
REROUTE_REQ=$(navcount 'reroute requested')
REROUTE_OK=$(navcount 'reroute applied')
REROUTE_ERR=$(navcount 'reroute failed')
ARRIVED=$(navcount 'arrived')
GPSLOST=$(navcount 'gps GOOD -> LOST')
GPSBACK=$(navcount 'gps LOST -> GOOD')
MANEUVERS=$(grep -oP 'VectorNav.*maneuver \K[0-9]+' "$OUT/logcat-drive.txt" 2>/dev/null | sort -un | wc -l)
DROPPED=$(grep -c 'dropped an implausible fix' "$OUT/logcat-drive.txt" 2>/dev/null | head -1 || true)
NAVPHASE=$(navcount 'phase PREVIEW -> NAVIGATING')

note "offroute=$OFFROUTE  reroute req/ok/err=$REROUTE_REQ/$REROUTE_OK/$REROUTE_ERR"
note "arrived=$ARRIVED  maneuvers=$MANEUVERS  gps lost/back=$GPSLOST/$GPSBACK  dropped fixes=$DROPPED"

[ "$NAVPHASE" -ge 1 ] && ok "navigation was entered" || bad "navigation was never entered"

# Did the injection actually reach the app? The single most important check
# here, and the one V4's web harness did not have — it reported 56 fps for a
# "drive" during which the app received one position.
if grep -q 'VectorMock.*START' "$OUT/logcat.txt" 2>/dev/null; then
  ok "the trace was replayed ($(grep -oP 'START fixes=\K[0-9]+' "$OUT/logcat.txt" | head -1) fixes)"
else
  bad "no replay started — was mock_location granted?"
fi
if [ "$MANEUVERS" -ge 2 ]; then
  ok "the vehicle moved through $MANEUVERS maneuvers"
else
  bad "only $MANEUVERS maneuver(s) — the vehicle did not move"
fi

echo "=== 6. per-scenario expectations ==="
expect_eq() { if [ "$2" = "$3" ]; then ok "$1 ($2)"; else bad "$1: expected $3, got $2"; fi; }
expect_ge() { if [ "$2" -ge "$3" ]; then ok "$1 ($2)"; else bad "$1: expected >= $3, got $2"; fi; }
expect_le() { if [ "$2" -le "$3" ]; then ok "$1 ($2)"; else bad "$1: expected <= $3, got $2"; fi; }

case "$SCENARIO" in
  scenario-a-city|scenario-b-stopgo|scenario-j-highway|scenario-k-dense)
    expect_eq "a clean drive does not reroute" "$REROUTE_REQ" 0
    expect_eq "a clean drive is never off route" "$OFFROUTE" 0
    expect_ge "arrival was detected" "$ARRIVED" 1
    ;;
  scenario-c-missed-turn)
    expect_ge "the missed turn was noticed" "$OFFROUTE" 1
    expect_eq "one deviation, one request" "$REROUTE_REQ" 1
    expect_ge "the new route was applied" "$REROUTE_OK" 1
    ;;
  scenario-d-wrong-road)
    expect_ge "the wrong road was noticed" "$OFFROUTE" 1
    expect_le "no reroute storm" "$REROUTE_REQ" 2
    ;;
  scenario-e-uturn)
    expect_eq "a U-turn on the same carriageway is not a deviation" "$OFFROUTE" 0
    expect_eq "no arrival while driving away from the destination" "$ARRIVED" 0
    ;;
  scenario-f-drift)
    expect_eq "urban-canyon drift does not reroute" "$REROUTE_REQ" 0
    expect_ge "arrival was still detected" "$ARRIVED" 1
    ;;
  scenario-g-jump)
    expect_eq "a reflected fix does not reroute" "$REROUTE_REQ" 0
    expect_ge "the implausible fix was dropped" "$DROPPED" 1
    ;;
  scenario-h-outage)
    expect_ge "the driver was told positioning was lost" "$GPSLOST" 1
    expect_ge "positioning recovered" "$GPSBACK" 1
    expect_eq "an outage does not reroute" "$REROUTE_REQ" 0
    ;;
  scenario-l-arrival)
    expect_ge "arrival was detected" "$ARRIVED" 1
    ;;
  long-run)
    expect_eq "one deviation, one request over 27 km" "$REROUTE_REQ" 1
    expect_ge "the new route was applied" "$REROUTE_OK" 1
    expect_ge "arrival at the end of a 27 km drive" "$ARRIVED" 1
    ;;
  *) note "no expectations recorded for $SCENARIO" ;;
esac

echo "=== 7. frame timing WHILE MOVING ==="
# The number V3 and V4 could not produce. FrameMeter reports every 5 s while
# NAVIGATING; each line is one 600-frame window.
grep -oP 'frames=\d+ hz=[0-9.]+ p50=[0-9.]+ms p95=[0-9.]+ms p99=[0-9.]+ms worst=[0-9.]+ms late=\d+\([0-9.]+%\)' \
  "$OUT/logcat-drive.txt" > "$OUT/frames.txt" 2>/dev/null
NFRAMES=$(wc -l < "$OUT/frames.txt")
if [ "$NFRAMES" -gt 0 ]; then
  python3 - "$OUT/frames.txt" "$SPEEDUP" <<'PYEOF' | tee "$OUT/frames-summary.txt"
import re, sys, statistics
rows = []
for line in open(sys.argv[1]):
    m = re.search(r'hz=([0-9.]+) p50=([0-9.]+)ms p95=([0-9.]+)ms p99=([0-9.]+)ms '
                  r'worst=([0-9.]+)ms late=(\d+)\(([0-9.]+)%\)', line)
    if m:
        rows.append(tuple(float(x) for x in m.groups()))
if not rows:
    sys.exit(0)
hz  = [r[0] for r in rows]; p50 = [r[1] for r in rows]
p95 = [r[2] for r in rows]; p99 = [r[3] for r in rows]
wor = [r[4] for r in rows]; late= [r[6] for r in rows]
bad_windows = sum(1 for x in late if x > 10.0)
print("        windows=%d (each 600 frames, ~5 s)" % len(rows))
print("        hz    median %.1f  min %.1f" % (statistics.median(hz), min(hz)))
print("        p50   median %.2f ms  worst window %.2f ms" % (statistics.median(p50), max(p50)))
print("        p99   median %.2f ms  worst window %.2f ms" % (statistics.median(p99), max(p99)))
print("        worst frame over the whole drive %.2f ms" % max(wor))
print("        late frames  median %.2f%%  worst window %.2f%%" % (statistics.median(late), max(late)))
print("        disturbed windows (>10%% late) %d of %d" % (bad_windows, len(rows)))
if sys.argv[2] != "1":
    print("        NOTE: time-compressed %sx - not a drive's frame budget" % sys.argv[2])
PYEOF
  # Judged on the DISTRIBUTION, not on the worst window.
  #
  # The first version failed a drive if any single window exceeded 10% late,
  # and the first real 1x run on the S24 read: 45 of 47 windows at or under
  # 1.0% late, one at 6.0%, one at 21.2%. Calling that "frames dropped while
  # moving" is not a fair description of a handset that is also running an OS
  # — a tile batch landing, a GC, the display dropping to 60 Hz for a moment.
  #
  # Nor is it weaker. It asserts two things instead of one: the typical window
  # has to be clean, AND disturbances have to stay rare. A regression that made
  # every window 8% late would pass the old rule and fail this one.
  MEDLATE=$(grep -oP 'late frames  median \K[0-9.]+' "$OUT/frames-summary.txt")
  BADW=$(grep -oP 'disturbed windows \(>10% late\) \K[0-9]+' "$OUT/frames-summary.txt")
  ALLW=$(grep -oP 'disturbed windows \(>10% late\) [0-9]+ of \K[0-9]+' "$OUT/frames-summary.txt")
  if [ -n "$MEDLATE" ] && [ "$(python3 -c "print(1 if $MEDLATE < 2 else 0)")" = "1" ]; then
    ok "typical window clean while moving (median ${MEDLATE}% late)"
  else
    bad "the typical window drops frames while moving (median ${MEDLATE:-?}% late)"
  fi
  if [ -n "$BADW" ] && [ -n "$ALLW" ] && \
     [ "$(python3 -c "print(1 if $BADW <= max(1, 0.1*$ALLW) else 0)")" = "1" ]; then
    ok "disturbances rare ($BADW of $ALLW windows over 10% late)"
  else
    bad "$BADW of ${ALLW:-?} windows dropped more than 10% of their frames"
  fi
else
  skipf "no frame reports — the app only measures while NAVIGATING"
fi

echo "=== 8. memory over the drive ==="
adb -s "$SERIAL" shell dumpsys meminfo $PKG 2>/dev/null > "$OUT/meminfo-after.txt"
PSS1=$(grep -oP 'TOTAL PSS:\s+\K[0-9]+' "$OUT/meminfo-after.txt" | head -1)
if [ -n "${PSS0:-}" ] && [ -n "${PSS1:-}" ]; then
  MB0=$((PSS0/1024)); MB1=$((PSS1/1024)); GROWTH=$((MB1-MB0))
  note "PSS ${MB0} MB -> ${MB1} MB over ${DUR}s of driving (${GROWTH:+$GROWTH} MB)"
  if [ "$MB1" -lt 700 ]; then ok "memory within budget"; else bad "PSS ${MB1} MB"; fi
  if [ "$GROWTH" -lt 150 ]; then ok "no runaway growth"; else bad "grew ${GROWTH} MB"; fi
else
  skipf "no meminfo"
fi

echo "=== 9. thermal and battery, where the device reports them ==="
# Best effort and labelled as such: these are whole-device numbers, so on a
# handset doing anything else they are not attributable to Vector.
TEMP=$(adb -s "$SERIAL" shell dumpsys thermalservice 2>/dev/null | grep -oP 'mValue=\K[0-9.]+' | head -1)
[ -n "$TEMP" ] && note "device temperature ${TEMP} C (whole device)" || note "no thermal readout"
# Anchored: an unanchored "temperature" matched every ACTION_BATTERY_CHANGED
# line the framework had logged that day, which is fifteen screens of somebody
# else's battery history in an artefacts directory.
adb -s "$SERIAL" shell dumpsys battery 2>/dev/null \
  | grep -E '^\s+(level|temperature|status|scale):' | sed 's/^/        /'

echo "=== 9b. cold launch with a saved journey ==="
# The regression this exists for crashed the app on launch, and nothing could
# have caught it anywhere else: `MainActivity.onCreate` needs a GL surface, so
# it is not reachable from the JVM suite at all.
#
# V5 added a journey that survives process death. Its "wait for a fix" poll used
# `mapView.postDelayed` and it is started from `onCreate`, BEFORE `mapView` is
# assigned — so the first launch with a saved journey died on
# `lateinit property mapView has not been initialized`. Which is exactly the
# situation the feature exists for: Android had killed the app mid-drive.
adb -s "$SERIAL" shell am force-stop $PKG
adb -s "$SERIAL" shell "run-as $PKG sh -c 'cat > shared_prefs/journey_probe.xml'" </dev/null 2>/dev/null
# Write a journey directly, with the app stopped so its cache cannot overwrite.
adb -s "$SERIAL" shell "run-as $PKG sed -i 's|</map>|<float name=\"journey_lng\" value=\"51.4986\" /><float name=\"journey_lat\" value=\"25.3208\" /><string name=\"journey_name\">Resume probe</string><long name=\"journey_at\" value=\"$(($(date +%s)*1000))\" /></map>|' shared_prefs/vector.xml" >/dev/null 2>&1
adb -s "$SERIAL" logcat -c
adb -s "$SERIAL" shell am start -n "$ACT" >/dev/null 2>&1
sleep 14
if adb -s "$SERIAL" shell pidof $PKG >/dev/null 2>&1; then
  ok "survived a cold launch with a saved journey"
else
  bad "died on a cold launch with a saved journey"
fi
RESUME=$(adb -s "$SERIAL" logcat -d -s "VectorNav:*" "AndroidRuntime:E" 2>/dev/null)
if echo "$RESUME" | grep -q "FATAL EXCEPTION"; then
  bad "crashed resuming a journey"
  echo "$RESUME" | grep -A6 "FATAL EXCEPTION" | head -12
else
  ok "no crash resuming a journey"
fi
if echo "$RESUME" | grep -q "journey resumed"; then
  ok "the saved journey was restored"
else
  note "journey not resumed (no fix within 30 s is a legitimate outcome here:"
  note "mock mode is off by now, so this depends on the handset's real GPS)"
fi
# Leave nothing behind: a probe journey must not be waiting for the driver.
adb -s "$SERIAL" shell am force-stop $PKG
adb -s "$SERIAL" shell "run-as $PKG sed -i -e '/journey_/d' shared_prefs/vector.xml" >/dev/null 2>&1

echo "=== 10. crashes ==="
CRASH=$(grep -cE "FATAL EXCEPTION|ANR in $PKG" "$OUT/logcat.txt" 2>/dev/null | head -1 || true)
[ "$CRASH" -eq 0 ] && ok "no crashes over the drive" || {
  bad "$CRASH crash line(s)"; grep -A6 "FATAL EXCEPTION" "$OUT/logcat.txt" | head -20; }

adb -s "$SERIAL" shell screencap -p /sdcard/vector-drive.png 2>/dev/null
adb -s "$SERIAL" pull /sdcard/vector-drive.png "$OUT/screen-end.png" >/dev/null 2>&1 \
  && note "final screen: $OUT/screen-end.png"

echo "=== 11. the device is left as it was found ==="
# A replay claims the fused provider via `setMockMode(true)`, and GMS holds that
# claim on the app's behalf until something releases it. A force-stop runs no
# lifecycle callbacks, so `MockDrive.stop()` never gets to — and the claim then
# outlives the app with nobody feeding it, which stops the fused provider
# producing locations FOR EVERY APP ON THE DEVICE.
#
# Measured on the S24 the morning after the V5 batch, which ended by killing the
# app mid-`long-run`: 14 h 44 m with no fix from any provider, GMS still holding
# `{fused, mock, 25.245259,51.600181, spd=27.78}` — the last fix of
# scenario-j-highway — and Vector reporting "Searching for GPS" forever. The app
# now releases a stale claim on its next launch (MockDrive.releaseStaleMockMode),
# so this step CHECKS that it did, and says so loudly if it did not. A harness
# that leaves the instrument broken invalidates whatever it measures next.
GLMS=com.google.android.location.internal.GoogleLocationManagerService
mocked() {
  adb -s "$SERIAL" shell dumpsys activity service $GLMS 2>/dev/null     | grep -qE 'last location \(fine\).*mock'
}
if mocked; then
  note "the fused provider is still mocked; launching once to release the claim"
  adb -s "$SERIAL" shell am force-stop $PKG
  adb -s "$SERIAL" shell am start -n "$ACT" >/dev/null 2>&1
  sleep 8
  adb -s "$SERIAL" shell am force-stop $PKG
fi
if mocked; then
  bad "the fused provider is STILL in mock mode — this handset will not produce"
  note "a real position for any app until it is cleared. Recover with:"
  note "  adb shell settings put secure location_mode 0"
  note "  adb shell settings put secure location_mode 3"
  note "  adb shell am force-stop com.google.android.gms"
else
  ok "mock mode released; the fused provider is back on real positions"
fi

echo
echo "=== $SCENARIO @ ${SPEEDUP}x — $pass passed, $fail failed, $skip skipped ==="
echo "=== artefacts in $OUT ==="
[ "$fail" -eq 0 ]
