package dev.vector.android

import dev.vector.geo.SimFix
import java.io.File
import org.junit.Test
import org.junit.Assert.assertTrue

/**
 * Writes each V5 driving scenario out as a CSV the device can replay.
 *
 * ## Why a test and not a script
 *
 * Because the scenarios must have exactly ONE definition. V5 §19 requires
 * simulation results and device results to be reported separately, and that
 * comparison is only meaningful if both came from the same trace — a
 * shell-script trace generator and a Kotlin one would drift within a session,
 * and the first divergence would look like a device finding.
 *
 * So [ScenarioTraces] is the single source, `DriveScenarioTest` drives it
 * through the navigation loop on the JVM, and this writes the identical fix
 * stream to disk for `scripts/simulate_drive.sh` to push to the handset and
 * replay through the real fused-location provider. Same seeds, same noise, same
 * outages, same timestamps.
 *
 * It is a `@Test` because that is the only entry point Gradle offers an
 * Android unit-test source set. It asserts on its own output rather than just
 * producing it — an exporter that silently writes an empty file would leave the
 * device harness measuring nothing, and that is precisely the failure mode
 * V4's web harness hit when a "drive" delivered one position.
 *
 * ```
 * ./gradlew :app:testDebugUnitTest --tests 'dev.vector.android.TraceExportTest'
 * ls vector-android/app/build/traces/
 * ```
 */
class TraceExportTest {

    private val outDir = File("build/traces")

    /**
     * `tMs,lng,lat,speedMs,bearingDeg,accuracyM`.
     *
     * An EMPTY speed or bearing means the receiver reported none, which is a
     * different fact from zero and the one Vector had two defects in. A format
     * that wrote `0` for both would make the device runs unable to reproduce
     * them.
     */
    private fun write(name: String, fixes: List<SimFix>, note: String) {
        outDir.mkdirs()
        val f = File(outDir, "$name.csv")
        f.printWriter().use { w ->
            w.println("# $name — $note")
            w.println("# generated by TraceExportTest from ScenarioTraces; do not hand-edit")
            w.println("tMs,lng,lat,speedMs,bearingDeg,accuracyM")
            for (x in fixes) {
                w.println(
                    "%d,%.7f,%.7f,%s,%s,%.1f".format(
                        x.tMs, x.position.lng, x.position.lat,
                        x.speedMs?.let { "%.2f".format(it) } ?: "",
                        x.bearingDeg?.let { "%.1f".format(it) } ?: "",
                        x.accuracyM,
                    )
                )
            }
        }
        val seconds = fixes.last().tMs / 1000
        println("wrote ${f.path}: ${fixes.size} fixes, ${seconds}s")
        assertTrue("$name is empty", fixes.size > 20)
        assertTrue("$name lasts only ${seconds}s", seconds > 20)
    }

    @Test
    fun `export every scenario for the device harness`() {
        // The list lives in [TraceCorpus] so that the exporter and
        // [TraceContractTest] cannot disagree about what the corpus is.
        val corpus = TraceCorpus.all()

        for (t in corpus) write(t.name, t.fixes, t.note)

        // The destinations, so the shell script does not have to parse GeoJSON.
        File(outDir, "destinations.txt").printWriter().use { w ->
            w.println("# scenario<TAB>lat,lon  — for `am start --es vectorDest`")
            for (t in corpus) w.println("${t.name}\t${t.destination}")
        }
        println("wrote ${File(outDir, "destinations.txt").path}")
    }
}
